Journey improvement
palharesgabriel/healise pull request #47
Opened 2019-11-26 13:40 UTC by AdautoP

2019-11-26 13:45 UTC, tavares1 submitted a review, later dismissed

2019-11-26 13:49 UTC, tavares1 submitted a review, later dismissed

2019-11-26 13:59 UTC, ViniciusDeep requested changes
SÓ O BÁSICO

2019-11-26 14:00 UTC, thiivalente submitted a review, later dismissed

2019-11-26 16:11 UTC, thiivalente requested changes

2019-11-26 16:11 UTC, thiivalente commented on MyBujo2.0/Business Rules/Utils/CoreDataManager.swift
> +                        return ($0.feeling, $0.number + 1)
You can use ternary operator:
```swift
return $0.feeling === feeling ? ($0.feeling, $0.number) : $0
```
Use the `===` if it is the same object reference

2019-11-27 11:45 UTC, palharesgabriel approved these changes

2019-11-27 11:46 UTC, merged